In [2]:
import pandas as pd
data={
'Tid':[1,2,3,4,5,6,7,8,9,10],
'Refund':['Yes','No','No','Yes','No','No','Yes','No','No','No'],
'Marital Status':['Single','Married','Single','Married','Divorced','Married','Divorced','Single','Married','Single'],
'Taxable Income':['125k','100k','70k','120k','95k','60k','220k','85k','75k','90k'],
'Cheat':['No','No','No','No','Yes','No','No','Yes','No','Yes']
}
df=pd.DataFrame(data)
print(df)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125k    No
1    2     No        Married           100k    No
2    3     No         Single            70k    No
3    4    Yes        Married           120k    No
4    5     No       Divorced            95k   Yes
5    6     No        Married            60k    No
6    7    Yes       Divorced           220k    No
7    8     No         Single            85k   Yes
8    9     No        Married            75k    No
9   10     No         Single            90k   Yes

In [3]:
print(df.iloc[[0,4,7,8]])

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125k    No
4    5     No       Divorced            95k   Yes
7    8     No         Single            85k   Yes
8    9     No        Married            75k    No

In [4]:
print(df.iloc[3:8])

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120k    No
4    5     No       Divorced            95k   Yes
5    6     No        Married            60k    No
6    7    Yes       Divorced           220k    No
7    8     No         Single            85k   Yes

In [5]:
print(df.iloc[4:9,2:5])

  Marital Status Taxable Income Cheat
4       Divorced            95k   Yes
5        Married            60k    No
6       Divorced           220k    No
7         Single            85k   Yes
8        Married            75k    No

In [7]:
print(df.iloc[:,1:4])

  Refund Marital Status Taxable Income
0    Yes         Single           125k
1     No        Married           100k
2     No         Single            70k
3    Yes        Married           120k
4     No       Divorced            95k
5     No        Married            60k
6    Yes       Divorced           220k
7     No         Single            85k
8     No        Married            75k
9     No         Single            90k

In [9]:
import pandas as pd
df=pd.read_csv("Iris.csv")
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [12]:
import pandas as pd
df=pd.read_csv("Iris.csv")
df.drop(4, axis=0, inplace=True)
df.drop(df.columns[3], axis=1, inplace=True)
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

In [21]:
import pandas as pd
data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

df = pd.DataFrame(data)
df.to_csv("employees.csv", index=False)

In [2]:
print("Shape of DataFrame:",df.shape)
print("Number of rows:",df.shape[0])
print("Number of columns:",df.shape[1])

Shape of DataFrame: (5, 10)
Number of rows: 5
Number of columns: 10

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 528.0+ bytes

In [4]:
df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [5]:
df.describe(include="all")

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
count,5.000000,5,5,5.000000,5.00000,5.000000,5,5,5.0,5.000000
unique,NaN,5,4,NaN,NaN,NaN,5,2,NaN,NaN
top,NaN,Alice,IT,NaN,NaN,NaN,2020-03-15,Male,NaN,NaN
freq,NaN,1,2,NaN,NaN,NaN,1,3,NaN,NaN
mean,103.000000,NaN,NaN,34.000000,60000.00000,7.400000,NaN,NaN,5500.0,4.100000
std,1.581139,NaN,NaN,5.612486,7905.69415,3.847077,NaN,NaN,1000.0,0.494975
min,101.000000,NaN,NaN,28.000000,50000.00000,3.000000,NaN,NaN,4500.0,3.500000
25%,102.000000,NaN,NaN,29.000000,55000.00000,4.000000,NaN,NaN,5000.0,3.800000
50%,103.000000,NaN,NaN,34.000000,60000.00000,8.000000,NaN,NaN,5000.0,4.000000
75%,104.000000,NaN,NaN,38.000000,65000.00000,10.000000,NaN,NaN,6000.0,4.500000
max,105.000000,NaN,NaN,41.000000,70000.00000,12.000000,NaN,NaN,7000.0,4.700000

In [6]:
print("First 5 rows:")
display(df.head(5))

print("Last 3 rows:")
display(df.tail(3))

First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [7]:
average_salary = df["Salary"].mean()
print("Average Salary:",average_salary)

Average Salary: 60000.0

In [8]:
total_bonus = df["Bonus"].sum()
print("Total Bonus:",total_bonus)

Total Bonus: 27500

In [9]:
youngest_age = df["Age"].min()
print("Youngest Employee Age:",youngest_age)

Youngest Employee Age: 28

In [10]:
highest_rating = df["Rating"].max()
print("Highest Performance Rating:",highest_rating)

Highest Performance Rating: 4.7

In [11]:
df_sorted = df.sort_values(by="Salary",ascending=False)
df_sorted

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [12]:
def performance_category(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"
df["Performance_Category"] = df["Rating"].apply(performance_category)
df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [13]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

In [16]:
df.rename(columns={"Employee_ID": "ID"}, inplace=True)
df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [17]:
employees_experience = df[df["Years_of_Experience"]>5]
print("Employees with more than 5 years of experience:")
display(employees_experience)

Employees with more than 5 years of experience:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [18]:
it_employees = df[df["Department"] == "IT"]
print("Employees belonging to IT department:")
display(it_employees)

Employees belonging to IT department:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

In [19]:
df["Tax"] = df["Salary"] * 0.10
df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

In [22]:
df.to_csv("employees_modified.csv", index=False)